version: '3.8'

services:
  frontend1:
    build: .
    ports:
      - "3000:3000"
    environment:
      REACT_APP_INSTANCE_ID: "Frontend 1" 
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - app-network

  frontend2:
    build: .
    ports:
      - "3001:3000"
    environment:
      REACT_APP_INSTANCE_ID: "Frontend 2" 
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - app-network

  frontend3:
    build: .
    ports:
      - "3002:3000"
    environment:
      REACT_APP_INSTANCE_ID: "Frontend 3"
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - app-network

  backend1:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: restaurante
      INSTANCE_ID: "Backend 1" 
    depends_on:
      - db
    networks:
      - app-network

  backend2:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: restaurante
      INSTANCE_ID: "Backend 2" 
    depends_on:
      - db
    networks:
      - app-network

  backend3:
    build: ./backend
    ports:
      - "5002:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: restaurante
      INSTANCE_ID: "Backend 3" 
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: restaurante
    ports:
      - "3306:3306"
    networks:
      - app-network
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=restaurante

  db_replica:
    container_name: db_replica
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: restaurante
    ports:
      - "3307:3306"
    networks:
      - app-network
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=restaurante
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend1
      - frontend2
      - frontend3
      - backend1
      - backend2
      - backend3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
